### ISSUE TITLE
Devcamp30: Code review 1

### ISSUE THREAD

**Issue by gabbyTI** [kazeems/propertycenter#1]
## Check if property exists in the DB
In the functions `getProperty()` , `updateProperty()`, `deleteProperty()` you missed checking if the property ID being passed in the request exists in the database.

that can cause an error or wrong data being returned to the user
````
...
$property = Property::find($propertyId);
// check if the returned property from the above statement is equal to null 
if($property == null){
  return response()->json([
      'success' => false,
      'message' => 'Property does not exist',
  ]);
}
...
````

## Minor logical error

in your `updateProperty()` validation rule for unique `name` yo should add this extra option, as shown below

```
...
public function updateProperty(Request $request, $propertyId) {
        $request->validate([
            'name' => ['required','min:5','unique:properties,name,'. $propertyId],
            ...
        ]);
...
```
What this does is to avoid running the `unique` validation on the existing `name` in the database.

NOTICE: Please reach out to me if you have questions

PS: noticed your alternative way of updating properties, that is alright too.

**Comment by kazeems** [comment]
Functions updated.
